//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETPHANQUYEN
    {
        public int IDCHITIETPHANQUYEN { get; set; }
        public int IDNHANVIEN { get; set; }
        public int IDQUYEN { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
        public virtual QUYEN QUYEN { get; set; }
    }
}
