//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETPHIEUTHU
    {
        public int IDCHITIETPHIEUTHU { get; set; }
        public int IDPHIEU { get; set; }
        public string NOIDUNG { get; set; }
        public Nullable<int> SOTIEN { get; set; }
    
        public virtual PHIEUTHU PHIEUTHU { get; set; }
    }
}
