//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHACHHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KHACHHANG()
        {
            this.PHIEUTHUs = new HashSet<PHIEUTHU>();
        }
    
        public int IDKHACHHANG { get; set; }
        public int IDTUYENTHU { get; set; }
        public int IDLOAIKH { get; set; }
        public int IDXAPHUONG { get; set; }
        public string MAKHACHHANG { get; set; }
        public string HOTEN { get; set; }
        public string DIACHI { get; set; }
        public string CMT { get; set; }
        public Nullable<System.DateTime> NGAYCAP { get; set; }
        public Nullable<System.DateTime> NGAYTAO { get; set; }
        public Nullable<System.DateTime> NGAYCHINHSUA { get; set; }
        public Nullable<bool> TRANGTHAI { get; set; }
    
        public virtual LOAIKH LOAIKH { get; set; }
        public virtual TUYENTHU TUYENTHU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUTHU> PHIEUTHUs { get; set; }
    }
}
