//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TTTT3Entities1 : DbContext
    {
        public TTTT3Entities1()
            : base("name=TTTT3Entities2")
        {
            this.Configuration.ProxyCreationEnabled = false;
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CHITIETPHANQUYEN> CHITIETPHANQUYENs { get; set; }
        public virtual DbSet<CHITIETPHIEUTHU> CHITIETPHIEUTHUs { get; set; }
        public virtual DbSet<KHACHHANG> KHACHHANGs { get; set; }
        public virtual DbSet<KYTHU> KYTHUs { get; set; }
        public virtual DbSet<LOAIKH> LOAIKHs { get; set; }
        public virtual DbSet<NHANVIEN> NHANVIENs { get; set; }
        public virtual DbSet<PHANQUYENTUYENTHU> PHANQUYENTUYENTHUs { get; set; }
        public virtual DbSet<PHIEUTHU> PHIEUTHUs { get; set; }
        public virtual DbSet<QUANHUYEN> QUANHUYENs { get; set; }
        public virtual DbSet<QUYEN> QUYENs { get; set; }
        public virtual DbSet<TUYENTHU> TUYENTHUs { get; set; }
        public virtual DbSet<XAPHUONG> XAPHUONGs { get; set; }
    }
}
