//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUTHU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHIEUTHU()
        {
            this.CHITIETPHIEUTHUs = new HashSet<CHITIETPHIEUTHU>();
        }
    
        public int IDPHIEU { get; set; }
        public int IDKHACHHANG { get; set; }
        public int IDKYTHU { get; set; }
        public int IDNHANVIEN { get; set; }
        public string MAUSOPHIEU { get; set; }
        public string KYHIEU { get; set; }
        public string TRANGTHAIPHIEU { get; set; }
        public Nullable<System.DateTime> NGAYTAO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETPHIEUTHU> CHITIETPHIEUTHUs { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual KYTHU KYTHU { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
