//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class XAPHUONG
    {
        public int IDXAPHUONG { get; set; }
        public int IDQUANHUYEN { get; set; }
        public string TENXAPHUONG { get; set; }
    
        public virtual QUANHUYEN QUANHUYEN { get; set; }
    }
}
